//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int orderId { get; set; }
        public int productId { get; set; }
        public Nullable<int> quantityOrdered { get; set; }
        public Nullable<decimal> priceEach { get; set; }
    
        public virtual Order order { get; set; }
        public virtual Product product { get; set; }
    }
}
