//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<System.DateTime> requiredDate { get; set; }
        public Nullable<System.DateTime> shippedDate { get; set; }
        public string comments { get; set; }
        public Nullable<int> customerId { get; set; }
        public string status { get; set; }
    
        public virtual Customer customer { get; set; }
    }
}
