//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class toysforboysEntities : DbContext
    {
        public toysforboysEntities()
            : base("name=toysforboysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> countries { get; set; }
        public virtual DbSet<Customer> customers { get; set; }
        public virtual DbSet<Orderdetail> orderdetails { get; set; }
        public virtual DbSet<Order> orders { get; set; }
        public virtual DbSet<Productline> productlines { get; set; }
        public virtual DbSet<Product> products { get; set; }
        public virtual DbSet<Admin> admins { get; set; }
    }
}
